### ISSUE TITLE
Login/auth. token retrieval takes 30 seconds with BIG-IP 15.1.6.1 Build 0.0.10 Point Release 1 => workaround

### ISSUE THREAD

**Issue by dschinnerl** [leonardobdes/BIGREST#20] opened 2022-07-26 07:48 UTC
Hi,

probably more a "FYI" for anyone who is also hitting the same issue we had. For some reason BIG-IP 15.1.6.1 Build 0.0.10 Point Release 1 has some odd behaviour if one requests an authentication token _and_ uses basic authentication to retrieve that token. It takes over 30 seconds for this request to complete! Funny part is that it works fast if one access the REST API via localhost / 127.0.0.1 (think ssh port forwarding). So I still think that this is just a bug in f5 because it worked with 14.x. (Using 1.4.0 but happens with 1.7.3 too.)

Anyway, the issue can be easily fixed by patching BIGREST: You need to edit `big.py` and `utils/utils.py`. Just search for "Required for 12.0.0, but not in 15.1.0".

```
# ---
# big.py

         # I guess those two lines can be commented also but didn't test (yet).
         if self.request_token is False:
            self.session.auth = (username, password)

         ...
  
         # Required for 12.0.0, but not in 15.1.0
         self.session.auth = (self.username, self.password)  # <= comment this line
         response = None
  
# ---
# utils.py
  
      response = requests.post(
        f"https://{device}/mgmt/shared/authn/login",
        json=data, verify=False, auth=auth)
  
# =>  
  
      response = requests.post(
        f"https://{device}/mgmt/shared/authn/login",
        json=data, verify=False)
```

Maybe I will provide some patch sometime. But I hope that information is helpful anyway for someone.

Kind regards,
Dietmar

---

```
diff -x '*.pyc' -x '*.bak' -r REDACTED/big.py ./big.py
439c439
<         # self.session.auth = (self.username, self.password)
---
>         self.session.auth = (self.username, self.password)
diff -x '*.pyc' -x '*.bak' -r REDACTED/utils/utils.py ./utils/utils.py
57c57
<         json=data, verify=False)
---
>         json=data, verify=False, auth=auth)
88c88
<         json=data, verify=False)
---
>         json=data, verify=False, auth=auth)
[REDACTED@REDACTED bigrest]$
```

**Comment by emalzer** [comment] 2022-07-28 07:53
Hi,

following https://support.f5.com/csp/article/K69245523 this does not look like a bug on the F5 side, it looks like 'works as designed', as they say that basic authentication may be slower and take more time to finish. So if token authentication should be used, then the login should not happen via basic authentication.

Greetings,
Eric

**Comment by leonardobdes** [comment] 2023-10-28 00:09
Thanks for the information, closing this now.

**Closed by leonardobdes** 2023-10-28 00:09 UTC
